<a href="https://colab.research.google.com/github/codingjobrice/AI/blob/main/PytorchBasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

def print_val(x):
  print("Type:",type(x))
  print("Shape:",x.shape)
  print("값: \n",x)
  print()


x= torch.rand(2,3,2)  # uniform : 0~1 사이 모든 값들이 나올 확률이 같음
print_val(x)

x=torch.randn(2,3)  # Gaussian
print_val(x)

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3, 2])
값: 
 tensor([[[0.1503, 0.7817],
         [0.8359, 0.8918],
         [0.9605, 0.8305]],

        [[0.5623, 0.0499],
         [0.5675, 0.9018],
         [0.7736, 0.8568]]])

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값: 
 tensor([[-0.6569, -0.9071,  0.0938],
        [-0.2503, -0.6924,  0.7894]])



In [5]:
x=torch.randperm(4)  # 0~n-1 까지 값을 원소로 갖는 배열 -> 랜덤 배열
print_val(x)

# [start,end) 구간을 step 단위로 나눠서 배열로 생성
x=torch.arange(0,3,step=0.5)
print_val(x)

Type: <class 'torch.Tensor'>
Shape: torch.Size([4])
값: 
 tensor([0, 1, 2, 3])

Type: <class 'torch.Tensor'>
Shape: torch.Size([6])
값: 
 tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])



In [6]:
print_val(torch.ones(3,4))
print_val(torch.zeros(3,4))

print_val(torch.Tensor(2,4))

Type: <class 'torch.Tensor'>
Shape: torch.Size([3, 4])
값: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Type: <class 'torch.Tensor'>
Shape: torch.Size([3, 4])
값: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 4])
값: 
 tensor([[2.0207e-35, 0.0000e+00, 3.7835e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.3733e-14, 6.4069e+02]])



In [7]:
print_val(torch.Tensor([2,3]))
print_val(torch.Tensor([[2,3],[3,4]]))

# 텐서 타입 변환
x=torch.FloatTensor(2,3)
print_val(x)

x=x.type_as(torch.IntTensor())
print_val(x)

Type: <class 'torch.Tensor'>
Shape: torch.Size([2])
값: 
 tensor([2., 3.])

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 2])
값: 
 tensor([[2., 3.],
        [3., 4.]])

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값: 
 tensor([[6.1589e-35, 0.0000e+00, 3.0000e+00],
        [4.0000e+00, 7.1220e+28, 6.9397e+22]])

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값: 
 tensor([[          0,           0,           3],
        [          4, -2147483648, -2147483648]], dtype=torch.int32)



In [8]:
# 텐서 크기 반환
torch.FloatTensor(3,4,5).size()


# numpy array -> torch tensor
import numpy as np

np_x=np.ndarray((2,3),dtype=int)
print_val(np_x)

x=torch.from_numpy(np_x)
print_val(x)

Type: <class 'numpy.ndarray'>
Shape: (2, 3)
값: 
 [[111432288         0         0]
 [        0         0         0]]

Type: <class 'torch.Tensor'>
Shape: torch.Size([2, 3])
값: 
 tensor([[111432288,         0,         0],
        [        0,         0,         0]])

